spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/caching_db
    username: shongo
    password: shongo
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db-changelog.xml
    drop-first: true
    contexts: test
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #generate_statistics: true
    hibernate:
      globally_quoted_identifiers: true
      ddl-auto: validate

# Application port
server:
  port: 8090


# Logging
logging:
  file: logs/log.log
